version: '3'
services:
  ontrack-db:
    image: 'postgres:latest'
  ontrack-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - ontrack-db
    environment:
      - PGUSER=postgres
      - PGHOST=ontrack-db
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - NODE_ENV=development
    restart: always
    ports:
      - '8080:8080'
